FROM node:19

WORKDIR /app
COPY ./package.json ./package.json
COPY ./server.js ./server.js
COPY ./models ./models
COPY ./routes ./routes
COPY ./controllers ./controllers
COPY ./middleware ./middleware
COPY ./db ./db
COPY ./config.env ./config.env 

RUN npm install
EXPOSE 4000
CMD ["node", "server.js"]